from enum import Enum, auto
from typing import TypeAlias


class Request(Enum):
    EXIT_APP = auto()
    EXIT_LOCAL_MENU = auto()
    MAIN_MENU = auto()
    SAVE = auto()
    MANAGE_PLAYER = auto()
    ADD_PLAYER = auto()
    REGISTER_PLAYER_DATA = auto()
    LIST_PLAYERS = auto()
    EDIT_PLAYER = auto()
    SELECTED_PLAYER = auto()
    CONFIRM = auto()
    MANAGE_TOURNAMENT = auto()
    GENERATE_MATCHES = auto()
    ADD_TOURNAMENT = auto()
    EDIT_TOURNAMENT = auto()
    LIST_TOURNAMENTS = auto()
    START_ROUND = auto()
    PRINT = auto()
    EXPORT = auto()
    KEEP_SELECTED_TOURNAMENT = auto()
    CHANGE_SELECTED_TOURNAMENT = auto()
    REGISTER_TOURNAMENT_DATA = auto()
    SELECTED_PATH = auto()
    LIST_MATCHES = auto()
    MANAGE_PARTICIPANTS = auto()
    ADD_PARTICIPANT = auto()
    DELETE_PARTICIPANT = auto()
    LIST_PARTICIPANTS = auto()
    REGISTER_MATCH_SCORE = auto()
    SELECTED_MATCH = auto()
    SELECTED_TOURNAMENT = auto()
    LIST_ROUNDS_SCORES = auto()
    ADD_MATCH_RESULT = auto()
    FIND_TOURNAMENT_BY_NAME = auto()
    FIND_TOURNAMENT_BY_LIST_ONGOING = auto()
    FIND_TOURNAMENT_BY_LIST_FUTURE = auto()
    FIND_TOURNAMENT_BY_LIST_PAST = auto()
    FIND_TOURNAMENT_BY_LIST_ALL = auto()


RequestAnswer: TypeAlias = Request | tuple[Request, list[object]]
